//ArtistSignUp
export const SET_ARTIST_SHOP = 'SET_ARTIST_SHOP'
export const SET_ARTIST_SHOP_ID = 'SET_ARTIST_SHOP_ID'
export const SET_ARTIST_AMERICAN_TRADITIONAL = 'SET_ARTIST_AMERICAN_TRADITIONAL'
export const SET_ARTIST_NEO_TRADITIONAL = 'SET_ARTIST_NEO_TRADITIONAL'
export const SET_ARTIST_TRIBAL = 'SET_ARTIST_TRIBAL'
export const SET_ARTIST_PHOTO_REALISM = 'SET_ARTIST_PHOTO_REALISM'
export const SET_ARTIST_JAPANESE = 'SET_ARTIST_JAPANESE'
export const SET_ARTIST_PORTRAIT = 'SET_ARTIST_PORTRAIT'
export const SET_ARTIST_GEOMETRIC = 'SET_ARTIST_GEOMETRIC'
export const SET_ARTIST_OTHER = 'SET_ARTIST_OTHER'
export const SET_ARTIST_DEFAULT = 'SET_ARTIST_DEFAULT'

//Posts
export const SET_POST_TEXT = 'SET_POST_TEXT'
export const SET_POST_IMAGE = 'SET_POST_IMAGE'
export const SET_POST_POSTED_BY = 'SET_POST_POSTED_BY'
export const SET_POST_ARTIST_ID = 'SET_POST_ARTIST_ID'
export const SET_POST_DEFAULT = 'SET_POST_DEFAULT'
export const SET_POSTS = 'SET_POSTS'

//Shops
export const SET_SHOP_ARTISTS = 'SET_SHOP_ARTIST'
export const SET_ARTISTS = 'SET_ARTISTS'
